<?php

/**
 * BaseTerapie
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $title
 * @property string $description
 * 
 * @method string  getName()        Returns the current record's "name" value
 * @method string  getTitle()       Returns the current record's "title" value
 * @method string  getDescription() Returns the current record's "description" value
 * @method Terapie setName()        Sets the current record's "name" value
 * @method Terapie setTitle()       Sets the current record's "title" value
 * @method Terapie setDescription() Sets the current record's "description" value
 * 
 * @package    studiosusani
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTerapie extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('terapie');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}