<?php

/**
 * TerapieTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TerapieTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TerapieTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Terapie');
    }
}