generator:
  class: sfDoctrineGenerator
  param:
    model_class:           News
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          news
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        title: { label: Titolo }
        description:    { label: Descrizione }
        
      list:
        title: Gestione delle News
        display: [=title, description]
        max_per_page: 10
        sort: [created_at, desc]
        batch_actions:
          _delete:
            label: Cancella
        object_actions:
          _edit:
            label: Modifica
            action: edit
            
          _delete:
            label: Cancella
            action: delete
            confirm: "Elimino la news selezionata?"
        actions:
          new: { label: Aggiungi, action: new }
        
        
      filter:
        class: false
      form:
        display:
          Content: [title, description]
        
      edit:
        title: Modifica di "%%title%%"
      new:
        title: Nuova News
